version: "3.7"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: low_code
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080" # host:container
    environment:
      ADMINER_DEFAULT_SERVER: mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "7001:6379"
    volumes:
      - redis:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    depends_on:
      - redis
    ports:
      - "8082:8001"
    environment:
      REDIS_INSIGHT_REDIS_HOSTS: redis-cluster:8083


volumes:
    mysql:
        driver: local
    redis:
        driver: local
