insert into mooc_categories (`code`, `name`, `productId`)
values ('cat_b_m', 'Business & Management', null),
       ('cat_c_s', 'Computer Science', null),
       ('cat_d_s', 'Data Science', null),
       ('cat_d', 'Design', null),
       ('cat_h', 'Health', null),
       ('cat_l', 'Language', null),
       ('cat_m_l', 'Math & Logic', null),
       ('cat_p_d', 'Personal Development', null),
       ('cat_p_s_e', 'Physical Science & Engineering', null),
       ( 'cat_s_s', 'Social Sciences', null),
       ( 'cat_t_p', 'Test Prep', null),
       ( 'cat_n', 'None', null),
       ( 'cat_java', 'Java', 2),
       ( 'cat_py', 'Python', 2),
       ( 'cat_dart', 'Dart', 2),
       ( 'cat_java_spring', 'Spring', 13);
insert into mooc_products (`name`, `description`, `price`)
values ('Business & Management 1', 'Learn how to use data to make better decisions', 10),
       ('Computer Science 2', 'Learn how to use data to make better decisions', 20),
       ('Computer Science 3', 'Learn how to use data to make better decisions', 30),
       ('Data Science 4', 'Learn how to use data to make better decisions', 40),
       ('Data Science 5', 'Learn how to use data to make better decisions', 50),
       ('Data Science 6', 'Learn how to use data to make better decisions', 60),
       ('Design 7', 'Learn how to use data to make better decisions', 70),
       ('Health 8', 'Learn how to use data to make better decisions', 80),
       ('Health 9', 'Learn how to use data to make better decisions', 90),
       ( 'Language 10', 'Learn how to use data to make better decisions', 100),
       ( 'Language 11', 'Learn how to use data to make better decisions', 110),
       ( 'Language 12', 'Learn how to use data to make better decisions', 120),
       ( 'Math & Logic 13', 'Learn how to use data to make better decisions', 130),
       ( 'Math & Logic 14', 'Learn how to use data to make better decisions', 140),
       ( 'Personal Development 15', 'Learn how to use data to make better decisions', 150),
       ( 'Physical Science & Engineering 16', 'Learn how to use data to make better decisions', 160),
       ( 'Social Sciences 17', 'Learn how to use data to make better decisions', 170),
       ( 'Test Prep 18', 'Learn how to use data to make better decisions', 180),
       ( 'Test Prep 19', 'Learn how to use data to make better decisions', 190),
       ( 'Test Prep 20', 'Learn how to use data to make better decisions', 200),
       ( 'None 21', 'Learn how to use data to make better decisions', 210),
       ( 'None 22', 'Learn how to use data to make better decisions', 220),
       ( 'None 23', 'Learn how to use data to make better decisions', 230),
       ('None 24', 'Learn how to use data to make better decisions', 240);
insert into mooc_product_categories (`product_id`, `category_id`)
values (1, 1),
       (2, 2),
       (3, 2),
       (4, 3),
       (5, 3),
       (6, 3),
       (7, 4),
       (8, 5),
       (9, 5),
       (10, 6),
       (11, 6),
       (12, 6),
       (13, 7),
       (14, 7),
       (15, 8),
       (16, 9),
       (17, 10),
       (18, 11),
       (19, 11),
       (20, 11),
       (21, 12),
       (22, 12),
       (23, 12),
       (24, 12);
insert into mooc_product_images (`product_id`, `image`)
values ('https://www.edx.org/sites/default/files/course/image/promoted/business-analytics-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/ai-for-everyone-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/ai-for-everyone-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/data-science-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/data-science-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/data-science-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/design-thinking-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/healthcare-analytics-1.jpg'),
       ('https://www.edx.org/sites/default/files/course/image/promoted/healthcare-analytics-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/learn-spanish-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/learn-spanish-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/learn-spanish-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/mathematical-thinking-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/mathematical-thinking-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/leadership-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/robotics-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/psychology-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/ielts-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/ielts-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/ielts-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/none-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/none-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/none-1.jpg'),
       ( 'https://www.edx.org/sites/default/files/course/image/promoted/none-1.jpg');